version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: wowme-api:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./API_volume:/image_service/images:rw
