name: Deployment workflow
on:
  push:
    branches: [main]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set Up ENV
        run: |
          echo "${{ secrets.SQL_URI }}" > .env
          echo "${{ secrets.SALT }}" >> .env
          echo "${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "${{ secrets.REDIS_DATABASE }}" >> .env
          echo "${{ secrets.REDIS_PORT }}" >> .env
          echo "${{ secrets.SERVER_IP }}" >> .env
          echo "${{ secrets.ROUTE_IP }}" >> .env

  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Docker
        run: |
          sudo docker-compose down
          sudo docker-compose up --build -d
          sudo docker system prune -a
